#!/bin/sh
cd location-context-service && ./gradlew test --quiet || exit 1
cd ../places-service && ./gradlew test --quiet || exit 1
cd ../planner-service && ./gradlew test --quiet || exit 1
echo "Все тесты прошли"
exit 0