spring.application.name=location-context-service
server.port=8081
spring.jackson.deserialization.accept-empty-string-as-null-object=true
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.ru.kholodov.locationcontextservice=DEBUG
geocoding.url=https://us1.locationiq.com/v1/search
geocoding.api-key=${GEOCODING_API_KEY:}