spring.application.name=location-context-service
server.port=8081
spring.jackson.deserialization.accept-empty-string-as-null-object=true
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.ru.kholodov.locationcontextservice=DEBUG
geocoding.url=https://us1.locationiq.com/v1/search
geocoding.api-key=${GEOCODING_API_KEY:}
isochrone.url=https://api.openrouteservice.org/v2/isochrones/foot-walking
isochrone.api-key=${ISOCHRONE_API_KEY:}
http.connect-timeout-ms=5000
http.read-timeout-ms=30000
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=1h

integration.places-base-url=http://localhost:8082
integration.planner-base-url=http://localhost:8083
integration.connect-timeout-ms=5000
integration.read-timeout-ms=15000